### ISSUE TITLE
VSCode extension created for brittany

### ISSUE THREAD

**Issue by MaxGabriel** [lspitzner/brittany#102]
Hi :)

This isn't actually an issue, but I created a VSCode extension for Brittany and I thought you (@lspitzner) or other Brittany users might be interested.

* [VSCode extension](https://marketplace.visualstudio.com/items?itemName=MaxGabriel.brittany)
* [Source](https://github.com/MaxGabriel/brittany-vscode-extension)

The extension supports formatting full documents and specific ranges of code. Since it's implemented with VSCode's formatting API, it automatically supports nice features like format-on-save, and can support future VSCode features like format-on-paste automatically.
 
(You can close this whenever)

**Comment by lspitzner** [comment]
Thanks! I have updated the README with a paragraph about editor integration, and mention your extension.
