### ISSUE TITLE
Use config file in closest parent

### ISSUE THREAD

**Issue by matthew-piziak** [lspitzner/brittany#119]
From the `README`:
>uses/creates user config file in `~/.config/brittany/config.yaml`; also reads `brittany.yaml` in current dir if present.

It would be nice to share project configuration settings with collaborators by placing a `brittany.yaml` in the root of the project, and have it be respected even if a save hook is fired in a child directory.

**Comment by lspitzner** [comment]
Fixed in 779a23c380d1ff3bc68642d91a367903d05aa6bd.

**Comment by asheshambasta** [comment]
@lspitzner IMHO, the description at this point can still be clarified further. What does "also" mean here and how are the 2 configurations taken into account? If clarified, I can make a PR to explain these nuances in the README.
