### ISSUE TITLE
Stylish-haskell style import and record formatting

### ISSUE THREAD

**Issue by ElvishJerricco** [lspitzner/brittany#12]
Stylish-haskell and Brittany *usually* get along fine. But there are rare occasions where they disagree (case statements with guards are the only one I know of). So if the user wants the features of both, they have to give precedence to one of the tools.

I personally only use `stylish-haskell` because of the formatting of imports and of record types. If Brittany did these things, I would just drop `stylish-haskell` altogether.

*(PS: Sorry for bombarding you with 4 issues today =P I've been using Brittany for a little while now, and I'm starting to want to make some changes / fixes, so I'm documenting them in the form of issues. We'll see if I have the time to get to any of them myself.)*

**Comment by lspitzner** [comment]
Fyi if you want to contribute, I have started adding some docs that might be helpful. See [`docs/implementation/bridoc-design.md`](https://github.com/lspitzner/brittany/blob/master/docs/implementation/bridoc-design.md)

**Comment by ElvishJerricco** [comment]
That's a good doc! Helps a ton, thanks.

**Comment by lspitzner** [comment]
have you made any progress on this? I might start on something for data/record types otherwise.

**Comment by lspitzner** [comment]
the ghc syntax tree again takes me some time to figure out. I had not realized how overloaded commas in record definitions are, e.g.

~~~~.hs
data Foo = Foo { a, b :: Int, c, d :: Bool }
~~~~

is valid. If you think you know haskell syntax, implement a formatter.

**Comment by tfausak** [comment]
Since there are separate issues for imports (#155) and records (#47), I'm going to close this issue.
