### ISSUE TITLE
Newline at the end of the file

### ISSUE THREAD

**Issue by pythonissam** [lspitzner/brittany#130]
Newline character is inserted automatically when I format code. How can I avoid this?

**Comment by lspitzner** [comment]
Isn't that a feature? Why would you want something different?

This can easily happen when using the standard `lines` function, which does not distinguish between these to cases:

~~~~.hs
Prelude> lines "abc\ndef"
["abc","def"]
Prelude> lines "abc\ndef\n"
["abc","def"]
~~~~

But `brittany` internally already avoids the use of the standard `lines` for this reason. So presuming that `brittany` is not at fault for this, I checked the parser output as seen by brittany (via `--dump-ast-full`) for 1) a file that has no terminating newline and 2) the exact same file but with a newline character appended, and it appears that the parser output (obtained from `ghc`(-`exactprint`)) simply does not distinguish the two cases.

So you might have to push somewhere further up in the dependency stream for this change. There is the alternative of hacking some workaround into brittany of course, but I am really no fan of mucking with the parsing logic without a very good reason.

**Comment by pythonissam** [comment]
I'm sorry. This bug seems to belong to the HIE. Thank you for the reply, anyway.
