### ISSUE TITLE
Q. Does brittany write to STDOUT by default all the time?

### ISSUE THREAD

**Issue by ifyouseewendy** [lspitzner/brittany#134]
Hi, I'm trying to fix the brittany support for ale (https://github.com/w0rp/ale/issues/1424). TLDR; We have a guess that brittany might write to file in place at sometime and change to STDOUT later.

By pulling and playing around locally, I've found that it writes to `display` for `0.9.0.0` and `0.8.0.3`. Due to a conflict with my local `base`, I could not install `0.8.0.2` to test it out. Would someone help me confirm this please? Does brittany output to STDOUT all the time, or not? If there was a change, what is the version.

Thanks!

**Comment by lspitzner** [comment]
yes. When not providing output path (older versions) or `--write-mode inplace`, the default behaviour was always to use stdout. I don't think there is a single commit where this was not the case.

**Comment by ifyouseewendy** [comment]
Cool, good to know that. Thanks for the quick reply!
