### ISSUE TITLE
Settings for `import statement` pretty-formatting?

### ISSUE THREAD

**Issue by pythonissam** [lspitzner/brittany#138]
Brittany formats the `import statements` like this:

```haskell
import           Import
import           Import.Common.DB.Sort                    ( updateSort )
```

Though We'd have liked to format it in this way:

```haskell
import           Import
import           Import.Common.DB.Sort (updateSort)
```

Is there any setting to achieve this?

**Comment by lspitzner** [comment]
We have been discussing a bit how it might make sense to separate the configuration of import layouting from the `IndentPolicy` setting in #135, and I am in general open to change things in that direction.

Your example is a bit short however to see what layouting you even want. Consider all the different testcases that currently exist [in our testsuite](https://github.com/lspitzner/brittany/blob/master/src-literatetests/10-tests.blt#L657) under the `group module.import` header. Could you explain what layout you would prefer for some of these more complex cases?

**Comment by lspitzner** [comment]
Ah, but there is a good reason for not depending on the longest module name: You generally don't want large diffs when adding/removing a single import statement. With the layouting you propose, you end up changing _all_ import lines when you add/remove the longest one. Two people do that in parallel, merge conflict, annoying waste of time.

In the rationale, [we discuss some cases where brittany default layouting does not avoid merge conflicts entirely](http://hexagoxel.de/postsforpublish/posts/2017-10-28-brittany-rationale.html#context-sensitivity-versus-least-newlines) but at least you get less lines used in exchange. I don't see any (similar) objective advantage for the layouting you propose there.

**Comment by pythonissam** [comment]
I see. For now, I close this issue. Thank you anyway.
