### ISSUE TITLE
Interesting alignment of nested records

### ISSUE THREAD

**Issue by expipiplus1** [lspitzner/brittany#140]
I noticed this interesting alignment of the `=`s in a nested record construction. I think that the `=`s belonging to `ApplicationInfo` look a little strange being indented less far than the `=`s belonging to the surrounding `InstanceCreateInfo`.

```haskell
createInstance :: IO VkInstance
createInstance =
  let ici = InstanceCreateInfo
        { vkPNext                   = Nothing
        , vkFlags                   = zeroBits
        , vkPApplicationInfo        = ApplicationInfo
          { vkPNext              = Nothing
          , vkPApplicationName   = Just "vulkan-example"
          , vkApplicationVersion = 0
          , vkPEngineName        = Nothing
          , vkEngineVersion      = 0
          , vkApiVersion         = VK_MAKE_VERSION 1 0 0
          }
        , vkPPEnabledLayerNames     = []
        , vkPPEnabledExtensionNames = []
        }
  in  _
```

Although it's not a direct fix, perhaps `=` alignment shouldn't persist across multiline expressions (such as `ApplicationInfo{..}` in this case.

**Comment by tuncer** [comment]
This looks consistent to me. The outer level's `=` column is that far right due to `vkPPEnabledExtensionNames`. And the inner column's alignment is determined by the length of `vkApplicationVersion`. That said, I understand how this may look odd at first sight, though what is the better alternative? I wouldn't want the inner alignment to be shifted to match that of `vkPPEnabledExtensionNames`. That would waste space.

Would it be acceptable to reorder fields so that `vkPApplicationInfo` comes first or last?

**Comment by lspitzner** [comment]
@expipiplus1 

(I, too, like the current behaviour and don't find it too strange, but whatever)

> Although it's not a direct fix, perhaps = alignment shouldn't persist across multiline expressions (such as ApplicationInfo{..} in this case.

If "in this case" means "for record update" (or construction, i think) then you could test if changing the `ColRecUpdate` bit above fixes this for you. And if you want, you can add another LayoutConfig field that controls this - I'd be fine with merging this. Yet more config, but pretty clear in what it affects, so fine.

Of course we could also think about the other fields (should each bool above be configurable?) So far I simply avoided this question by choosing an (opinionated) default.

**Comment by roman** [comment]
> Would it be acceptable to reorder fields so that vkPApplicationInfo comes first or last?

I would agree to have `vkPApplicationInfo` being last would improve readability a bit

**Comment by expipiplus1** [comment]
Thinking about it a bit more, I think you're both right and this is a non-issue.

Thanks for the terrific library!
