### ISSUE TITLE
Handle Control.Lens pipelines cleanly

### ISSUE THREAD

**Issue by mezuzza** [lspitzner/brittany#149]
`Control.Lens.Operators` provides a number of different operators that are meant to act as assignments. It would be nice if brittany could smartly decide where to line break so that the operators feel like actual assignment.

Examples:
```
import Control.Lenses
import Data.Map

data Bar = Bar
         { _fieldA :: Maybe Int
         , _fieldB :: Map Char Bool
         }
makeLenses ''Bar

foo :: State (Int, [String], Bar) ()
foo = do
    fullState <- get
    _2 <>= ["adding to this log"]
    _3 . fielldA ?= Just 2
    _3 %= \x ->
      x & fieldA .~ (x ^. fieldB . at 'c')
        & fieldB . at 'a' ?~ (fullState ^. _1)
        & fieldB . at 'b' .~ Nothing
```

Current output (version 0.9.0.1):
```
import Control.Lenses
import Data.Map

data Bar = Bar
         { _fieldA :: Maybe Int
         , _fieldB :: Map Char Bool
         }
makeLenses ''Bar

foo :: State (Int, [String], Bar) ()
foo = do
  fullState <- get
  _2 <>= ["adding to this log"]
  _3 . fielldA ?= Just 2
  _3 %= \x ->
    x
      &  fieldA
      .~ (x ^. fieldB . at 'c')
      &  fieldB
      .  at 'a'
      ?~ (fullState ^. _1)
      &  fieldB
      .  at 'b'
      .~ Nothing
```

One example of better output. This is just an example and not the only layout that would be more reasonable. However, we have to agree that this version is better than the one above. 
```
import Control.Lens
import Data.Map

data Bar = Bar
         { _fieldA :: Maybe Int
         , _fieldB :: Map Char Bool
         }
makeLenses ''Bar

foo :: State (Int, [String], Bar) ()
foo = do
    fullState    <- get
    _2           <>= ["adding to this log"]
    _3 . fielldA ?= Just 2
    _3           %= \x ->
      x & fieldA          .~ (x ^. fieldB . at 'c')
        & fieldB . at 'a' ?~ (fullState ^. _1)
        & fieldB . at 'b' .~ Nothing
```

Obviously, this is a little hard to do in the general case. Among the problems:

1. It's not clear when the semantics of infix operators warrant alignment for arbitrary cases. 
2. Where do you align when operators are not the same length? Lenses in particular provides operators from two to five characters long e.g. (.\~), (^@.), (<<//\~), etc.
3. How should these interact when operators come from different libraries?

There are a few possible solutions, but here are three suggestions:

1. Use the operator's precedence to align intelligently.
2. Implement a special case for known popular libraries. Two that come to mind immediately are `Control.Lens` and `Data.Aeson` which was reported in #85. 
3. Add some sort of plugin architecture that allows a library to include an alignment configuration for operators.

Finally, it is also possible to simply treat all infix operators the same. This seems to match the current behavior, however it's pretty clear that all operators are not the same in the eyes of the haskell community. I'd also say that (1) is probably the best bet in terms of a generic solution with low-ish complexity. I mention the other two just for completeness in documentation. I think they are pretty poor solutions when (1) can likely provide a pretty darn good approximation.

**Comment by lspitzner** [comment]
Very good analysis, and in comes very close to what we discussed in #79.

~~~~
foo :: State (Int, [String], Bar) ()
foo = do
    fullState    <- get
    _2           <>= ["adding to this log"]
    _3 . fielldA ?= Just 2
    _3           %= \x ->
      x & fieldA          .~ (x ^. fieldB . at 'c')
        & fieldB . at 'a' ?~ (fullState ^. _1)
        & fieldB . at 'b' .~ Nothing
~~~~

is a nice goal, while indeed not a trivial one (i think it would need some work even with a precedence-respecting layouter due to the alignments).

As I mentioned in [my last comment in the other issue](https://github.com/lspitzner/brittany/issues/79#issuecomment-352259480), there is a pretty clear first step to make: write the algorithm that restructures the AST according to some precedence input (the origin of which we can discuss/improve upon later.)

On that note, it might be worth checking if there is something in the ghc source we can re-use here. Although we might need to distinguish even between "grouping due to precedence" and "grouping due to fixity" for layouting-purposes, and I am not sure the compiler cares for that distinction. Still, worth a look.

**Comment by mezuzza** [comment]
Apologies, I missed that ticket. Might be worth closing two of this, #79, and #85 for clearer records. #79 sounds like the right root ticket to me.
