### ISSUE TITLE
Some weird preceding printing occurring

### ISSUE THREAD

**Issue by ElvishJerricco** [lspitzner/brittany#15]
Simple test case:

```haskell
-- Test.hs
module Test where

data X = X
```

Output:

```
$ brittany Test.hs
["","","data X = X"]
-- Test.hs
module Test where

data X = X

```

Not sure what that's about...

**Comment by lspitzner** [comment]
Thanks. Never noticed, because my default testing ignores stderr. Now I wonder if I can make git warn me when making any commit containing non-commented "trace" strings.. someone must have written such a hook already.

**Comment by tfausak** [comment]
You could write your own `trace` functions and mark them as deprecated like [`undefined` in ClassyPrelude](https://www.stackage.org/haddock/lts-8.4/classy-prelude-1.2.0.1/ClassyPrelude.html#v:undefined).

**Comment by lspitzner** [comment]
Yeah that is certainly a better idea than hooks. I'll have to add something along those lines to qualified-prelude.
