### ISSUE TITLE
Update ghc-exactprint upper bound

### ISSUE THREAD

**Issue by alanz** [lspitzner/brittany#165]
ghc-exactprint-0.5.7.0 is now on hackage.

It is functionally identical to 0.5.6.1, but also supports GHC 8.6

**Comment by lspitzner** [comment]
#179 is merged, but we still want to make sure to have https://github.com/alanz/ghc-exactprint/pull/68 included in the next brittany release.

**Comment by lspitzner** [comment]
Fixed in 393258036f40de49a05b06a23e1cdb2290d3d9f4.
