### ISSUE TITLE
Non-idempotent: error when using (correct) output as input

### ISSUE THREAD

**Issue by ChickenProp** [lspitzner/brittany#169]
The following code formats correctly on https://hexagoxel.de/brittany/, moving `$thThing` down to the next line. But then attempting to format the output gives the error "unknown node: HsSpliceE{}". I guess related to #90, but doesn't use quasiquotes.

```haskell
testFunc :: IO Bar
testFunc = do
  someVariable <- someLongFunctionName $thThing
    "long argument to force thThing to move down"
  return someVariable
```

**Comment by eborden** [comment]
`$thThing` is being interpreted as a template haskell splice. Does your default extensions have this enabled?

**Comment by ChickenProp** [comment]
It has -XTemplateHaskell in options_ghc, if that's what you mean?

**Comment by eborden** [comment]
Posting your `brittany --dump-config` and cabal file here could be helpful. As well as enumerating any pragmas that are listed in the source file.

**Comment by lspitzner** [comment]
Yeah, this is #90. In the syntax tree, "$thThing" is `HsSpliceE HsUntypedSplice{}`, while `[blub|asd|]` is `HsSpliceE HsQuasiQuote{}`.

I'll close this as duplicate, but nonetheless thanks for reporting. I'll read it as another bump for #90 :)
