### ISSUE TITLE
Incorrect comment placement after formatting a multiline list.

### ISSUE THREAD

**Issue by barrucadu** [lspitzner/brittany#18]
It looks like if you have a comment on the penultimate line of a multi-line list, the comment gets pushed outside the list:

```diff
 -- | Predicates for the various autocheck functions.
 autocheckCases :: Eq a => [(String, Predicate a)]
 autocheckCases =
-  [ ("Never Deadlocks",   representative deadlocksNever)
-  , ("No Exceptions",     representative exceptionsNever)
-  , ("Consistent Result", alwaysSame) -- already representative
-  ]
+  [ ("Never Deadlocks", representative deadlocksNever)
+  , ("No Exceptions", representative exceptionsNever)
+  , ("Consistent Result", alwaysSame)
+  ] -- already representative
```

**Comment by lspitzner** [comment]
Right, thanks for reporting. I think I really ought to add some more testing around this; i think there are some variations of this bug around.

(This originates from the goal of being able to transform end-of-line commas in such literals to start-of-line-ones while preserving comment placement - it gets messy.)
