### ISSUE TITLE
"Loaded package environment from..." pollutes the output

### ISSUE THREAD

**Issue by TomMD** [lspitzner/brittany#183]
Running brittany in a directory with .ghc.env... files yields ugly output such as:

```
Loaded package environment from /home/.../.ghc.environment.x86_64-linux-8.4.3
```

Which breaks lots of automated uses of brittany.

I see this is a [feature in GHC](https://ghc.haskell.org/trac/ghc/ticket/15145) and whichever library is using the GHC API (guessing here) should probably have an option for turning down the verbosity.

**Comment by alanz** [comment]
Are you using the version that uses ghc-exactprint-0.5.8.0? It has a workaround for that.

**Comment by TomMD** [comment]
Ah, indeed. The Brittany package on Hackage just hasn't been updated yet.
