### ISSUE TITLE
Brittany fails on import list containing Type Operators /  Infix Constructor

### ISSUE THREAD

**Issue by fendor** [lspitzner/brittany#191]
Brittany version: 
brittany 0.11.0.0 pulled from NixOS.

Also haskell-ide-engine from one of the latest [commits](https://github.com/haskell/haskell-ide-engine/commit/e71a89880ec9ec23e07f2c27f8efe0ea6ae60907) has the same problem.
E.g. can not format the code containing the import with `(:.)(..)`.
Haven't tested it from source, though. Too many build problems related to NixOS.

Example

```haskell
import Data.Array.Repa ((:.)(..))
```

Expected:

```haskell
import          Data.Array.Repa      ((:.)(..))
```
or something like that.

Actual:
```bash
Loaded package environment from /home/user/Documents/haskell/project/.ghc.environment.x86_64-linux-8.4.3
Loaded package environment from /home/user/Documents/haskell/project/.ghc.environment.x86_64-linux-8.4.3
ERROR: brittany pretty printer returned syntactically invalid result.
```

I hope, it is not a duplicate, I am sorry if it is, but I couldnt find a similar issue so far.

**Comment by matt-noonan** [comment]
This appears to be the same issue as #170, and is now resolved.
