### ISSUE TITLE
Add emacs integration info to readme

### ISSUE THREAD

**Issue by patrl** [lspitzner/brittany#196]
A little while back, I requested that `brittany` be made the default haskell formatter for the `emacs-format-all-the-code` package (see [this thread](https://github.com/lassik/emacs-format-all-the-code/issues/5#issuecomment-421590632)). This is probably the easiest way for emacs users to integrate brittany into their workflow, so perhaps it should be added to to "editor integration" section of the readme.

**Comment by tfausak** [comment]
Fixed by  #221.
