### ISSUE TITLE
Support pattern synonyms

### ISSUE THREAD

**Issue by mkaput** [lspitzner/brittany#199]
As of 9d91523 Brittany crashes on pattern synonyms:

```haskell
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE ViewPatterns #-}

module Main where

pattern Foo pk <- (Just pk)
```

**Comment by tomjaguarpaw** [comment]
I would like this too, please!

**Comment by asheshambasta** [comment]
I might be doing something really wrong; but it seems to me that is also removes `pattern` in import statements: 
```haskell
import           Data.Types                     ( PairData'(..)
                                                , pattern OnlineP
                                                )
```

Becomes: 

```
import           Data.Types                     ( PairData'(..)
                                                , OnlineP
                                                )
```

Which is invalid. 
Adding `--brittany-disable-next-binding` anywhere before this import statement makes no difference.

**Comment by tfausak** [comment]
The pattern import thing has been fixed. See #204. 

As for the original issue, this is enough to trigger the problem:

``` hs
{-# LANGUAGE PatternSynonyms #-}
pattern Foo pk <- (Just pk)
```

**Comment by runarorama** [comment]
Any hints on where to look if I wanted to take a stab at fixing this issue?

**Comment by andys8** [comment]
This fix was merged in march, but there was no release since then. Is there a plann to do a release @lspitzner ? :)
