### ISSUE TITLE
Register with Stackage

### ISSUE THREAD

**Issue by begriffs** [lspitzner/brittany#2]
Thanks for making this indenter!

I'd like to use it in https://github.com/begriffs/haskell-vim-now rather than hindent, and the installer for haskell-vim-now uses Stack to build helper tools.

**Comment by metaleap** [comment]
Yeah about time `stack install brittany` gets supported! =)

**Comment by begriffs** [comment]
This is probably waiting for #29 anyway, but after that is done here are the steps to get this on stackage - https://github.com/fpco/stackage#add-your-package

Looks like one of those steps does require @lspitzner to review their maintainer agreement.

**Comment by lspitzner** [comment]
The package is on hackage now/#29 is closed. For stackage, i think the only remaining dependency from other maintainers is `monad-memo`. I have opened https://github.com/EduardSergeev/monad-memo/issues/2.

The maintainer agreement is a joke now, imo - there is nothing to agree to anymore. Regardless, I have no issues with becoming stackage maintainer.

**Comment by lspitzner** [comment]
There also is the option to just get rid of monad-memo: It is used in one module only, and has only some few references. Should be straight-forward to locally make a newtype and reimplement the specific `Memo.memo` function. Pull requests welcome.

**Comment by lspitzner** [comment]
I admit that it is sad that this is still unresolved. Unfortunately I don't want to take over monad-memo or spend the time replacing/removing the dependency. Maybe some stack user could help here?

**Comment by tfausak** [comment]
I think the easiest way forward is adding monad-memo to Stackage too. It hasn't been touched in a while, which suggests it's either complete or abandoned. It doesn't have that many dependencies, and the ones it does have are pretty standard. I'll add it myself if no one beats me to it.

**Comment by tfausak** [comment]
monad-memo is now in Stackage: https://github.com/fpco/stackage/pull/2982

**Comment by lspitzner** [comment]
ah, and you count on the package never breaking, because you wouldn't even be able to upload a fix to hackage? fair enough, i guess.

I'll see soon about releasing butcher,czipwith and brittany to stackage.

**Comment by lspitzner** [comment]
`brittany` is in stackage since a couple of days and should be included in the latest nightlies.

**Comment by begriffs** [comment]
@lspitzner thank you, I appreciate your work on this!
