### ISSUE TITLE
Can't handle INLINE pragma on the first line of a where clause

### ISSUE THREAD

**Issue by barrucadu** [lspitzner/brittany#20]
This works fine:

```haskell
answer :: Int
answer = x where
  x = 42
  {-# INLINE x #-}
```
This causes brittany to die with "ERROR: brittany pretty printer returned syntactically invalid result."

```haskell
answer :: Int
answer = x where
  {-# INLINE x #-}
  x = 42
```

**Comment by lspitzner** [comment]
it boils down to this being a syntax error:

~~~~.hs
foo = r
 where
   {-# INLINE r #-}
  r = undefined
~~~~

which I did not anticipate. Pragmas don't count as comments and affect the layouting-rule? Pragmas count as comments but still affect the layouting-rule? I'll have to consult the report for this,,

(The fact that the pragma is placed there in the output might be a minor error nonetheless, I'll have to look into this. Perhaps I can tweak the where-clause-layouting to get rid of this.)

**Comment by lspitzner** [comment]
> Some compiler implementations support compiler pragmas, which are used to give additional instructions or hints to the compiler, but which do not form part of the Haskell language proper and do not change a program’s semantics

([2010 report](https://www.haskell.org/onlinereport/haskell2010/haskellch12.html#x19-18800012))

Well.. syntax error vs no syntax error does count as a change in semantics, doesn't it, heh.

**Comment by ElvishJerricco** [comment]
Then it certainly seems like a bug in GHC that this is a syntax error;
should probably just be a warning like "Warning: incorrect indentation
invalidating INLINE pragma."

**Comment by lspitzner** [comment]
for those curious, my current understanding regarding pragmas: they are like optional keywords. the compiler is free to interpret them either as comments (ignore them, effectively) or consider them like keywords including corresponding lexical/syntactical "powers". giving them a lexical look similar to comments has two advantages: 1) compiler implementors are free to ignore that part and have them treated as comments 2) adding new pragmas is much less of an issue than adding new keywords to the language.

this is not very clear in the 2010 report, but with this understanding the above error itself (from ghc) is valid.
