### ISSUE TITLE
brittany insists on ExplicitNamespaces declared at top of file and nowhere else.

### ISSUE THREAD

**Issue by dspies-leapyear** [lspitzner/brittany#202]
When my `package.yaml` file already includes `TypeFamilies` and `TypeOperators`, `brittany` complains when I do an explicit import:

```
import Data.Singletons.Prelude(type (++))
```

even though `GHC` is fine with this.

`Illegal keyword 'type' (use ExplicitNamespaces to enable)`

Even if I add `ExplicitNamespaces` to my `package.yaml`/`cabal` file, `brittany` _still_ complains. It only seems to be happy if I put it as a pragma at the top of the file.

**Comment by tfausak** [comment]
Brittany doesn't read the default extensions from your `package.yaml` or `*.cabal` file. You'll have to either pass in your extensions as options or set them in your `brittany.yaml` config. See this section of the readme: https://github.com/lspitzner/brittany/blob/6c187da/README.md#usage

**Comment by dspies-leapyear** [comment]
That's strange. I regularly put all of (among other things)
```
LambdaCase
GADTs
ViewPatterns
ExplicitForAll (via ScopedTypeVariables and RankNTypes)
```
as default extensions in my package.yaml file
and I've never had `brittany` complain about any of them.

**Comment by dspies-leapyear** [comment]
It didn't, but in any case the fix works. I should close this.
