### ISSUE TITLE
Format type applications with a space before @

### ISSUE THREAD

**Issue by artempyanykh** [lspitzner/brittany#205]
Hey there! Hope you're doing well!

When using generic-lens, the following 
```haskell
dat ^. field @"fieldName"
```
gets reformatted into this
```haskell
dat ^. field@"fieldName"
```
The latter produces an error 
```
Pattern syntax in expression context: field@"fieldName"
Type application syntax requires a space before '@'
```

Is there a way to change this behaviour? I'm using brittany-0.11.0.0 from LTS-12.14.

**Comment by ChickenProp** [comment]
I don't have this behaviour. I don't get `field@"fieldName"` reformatted as `field @"fieldName"`, but I don't get it reformatted the other way, either.

I'm using a more recent version (8c5cce5070), but also, do you have `-XTypeApplications` in your brittany.yaml?

**Comment by artempyanykh** [comment]
I've tried again now, and indeed the space before `@` is preserved. Although, `-XTypeApplications` was already in my brittany.yaml 🤨
Anyway, looks like it's my mistake (maybe didn't actually save brittany.yaml buffer 🤷‍♂️ ) Sorry, for the trouble, I'll close the issue.
