### ISSUE TITLE
invalid output when deriving instances for an associated newtype family instance

### ISSUE THREAD

**Issue by dspies-leapyear** [lspitzner/brittany#207]
Trying to format a typeclass instance which includes data-family declarations and getting:

`Brittany error - invalid output`

```
{-# LANGUAGE TypeFamilies #-}

module Lib where

class Foo x where
  data Bar x
  bar :: x -> Bar x

instance Foo () where
  newtype Bar () = Baz ()
    deriving (Eq, Ord, Show)
  bar = Baz
```

**Comment by dspies-leapyear** [comment]
It looks like it's specifically `deriving` on a `newtype` that causes it to break. Updated with a MWE. PTAL

**Comment by tfausak** [comment]
Seems like this only affects `newtype`s. Changing it to `data` works as expected.

``` hs
-- succeeds
instance C () where
 data T () = T ()
  deriving Eq

-- fails
instance C () where
 newtype T () = T ()
  deriving Eq

-- using `--output-on-errors` gives
instance C () where
  newtype T () = T ()
  deriving Eq
```

**Comment by cdparks** [comment]
I ran into this not with `deriving` but with nesting the field selector on the last line. This module spits out a `ERROR: brittany pretty printer returned syntactically invalid result`:

```haskell
class Foo a where
  data family Bar

instance Foo Int where
  newtype Bar Int = BarInt
    { unBarInt :: Int
    }
```

With `--output-on-errors`, I'm getting:

```haskell
class Foo a where
  data family Bar

instance Foo Int where
  newtype Bar Int = BarInt
  { unBarInt :: Int
  }
```

Note that the position of the braces is now a syntax error.

@tfausak happy to file a separate bug or just pile onto this one

**Comment by tfausak** [comment]
Seems like it's probably the same root cause.

**Comment by lspitzner** [comment]
uh oh

https://github.com/lspitzner/brittany/blob/4b673d1d9db70e3a0d01a6b3315618e30b887c78/src/Language/Haskell/Brittany/Internal/Layouters/Decl.hs#L1038-L1041
