### ISSUE TITLE
Alignment of <-s is really aggressive

### ISSUE THREAD

**Issue by barrucadu** [lspitzner/brittany#21]
When aligning things by hand, I usually decide not to if it would introduce "too much" spacing (where "too much" is some fuzzy thing based on gut feeling).

This is definitely too much:

```diff
   (finalCtx, trace, finalAction) <- runThreads sched memtype ref ctx
-  out <- readRef ref
+  out                            <- readRef ref
```

Perhaps there could be a configurable maximum number of spaces, with alignment not done if it would introduce more than that many?

**Comment by lspitzner** [comment]
good idea. There is also "don't do alignment when the things being aligned are apart more than x lines", which is like the vertical version of this.

**Comment by barrucadu** [comment]
For the vertical version, I think it would be worth distinguishing lines of comments/whitespace, and lines of code.

For example, I align the `::`s here because there are only a few lines of comments between them:

```haskell
-- | DPOR execution is represented as a tree of states, characterised
-- by the decisions that lead to that state.
data DPOR = DPOR
  { dporRunnable :: Set ThreadId
  -- ^ What threads are runnable at this step.
  , dporTodo     :: Map ThreadId Bool
  -- ^ Follow-on decisions still to make, and whether that decision
  -- was added conservatively due to the bound.
  , dporDone     :: Map ThreadId DPOR
  -- ^ Follow-on decisions that have been made.
  , dporSleep    :: Map ThreadId ThreadAction
  -- ^ Transitions to ignore (in this node and children) until a
  -- dependent transition happens.
  , dporTaken    :: Map ThreadId ThreadAction
  -- ^ Transitions which have been taken, excluding
  -- conservatively-added ones. This is used in implementing sleep
  -- sets.
  , dporAction   :: Maybe ThreadAction
  -- ^ What happened at this step. This will be 'Nothing' at the root,
  -- 'Just' everywhere else.
  } deriving (Eq, Show)
```

But I don't align the `->`s in the case here, because there is code in the way:

```haskell
       case M.lookup tid' (dporDone dpor) of
         Just dpor' ->
           let done = M.insert tid' (grow state' tid' rest dpor') (dporDone dpor)
           in dpor { dporDone = done }
         Nothing ->
           let taken = M.insert tid' a (dporTaken dpor)
               sleep = dporSleep dpor `M.union` dporTaken dpor
               done  = M.insert tid' (subtree state' tid' sleep trc) (dporDone dpor)
           in dpor { dporTaken = if conservative then dporTaken dpor else taken
                   , dporTodo  = M.delete tid' (dporTodo dpor)
                   , dporDone  = done
                   }
```

**Comment by lspitzner** [comment]
yes, in fact i think _not_ ignoring comments for this test would be much harder than what you propose, given how things are implemented :)

**Comment by lspitzner** [comment]
> , _lconfig_alignmentLimit            = coerce (30 :: Int)
> , _lconfig_alignmentBreakOnMultiline = coerce True

i hope these defaults are fine. please report if this doesn't work as expected.
