### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by eborden** [lspitzner/brittany#211]
`brittany` has fallen out of stackage because `0.11.0.0` does not build with GHC `8.6.x`. There are two paths to getting it back in.

1. Cut a release of `0.11.x` that includes the necessary changes for `8.6.x`
2. Cut a major release from `master`

I'm not sure which path you'd like to follow. 1 is a path that may require some work, but will continue support for that branch of the tool for users that aren't ready for major feature upgrades. 2 is the path of least resistance, but cutting a release requires more thought than just stackage LTS pressure.

**Comment by tfausak** [comment]
Closing this for now. Keep your eyes peeled 😉

**Comment by lspitzner** [comment]
See https://github.com/commercialhaskell/stackage/pull/4635
