### ISSUE TITLE
Format Brittany's source code with Brittany

### ISSUE THREAD

**Issue by tfausak** [lspitzner/brittany#238]
It would be nice if Brittany could be "self hosting" in that it could format its own source. Doing so would give a lot of confidence that things aren't broken, and also stand as a good example of what Brittany's output looks like.

**Comment by eborden** [comment]
I'm curious if using https://restyled.io/ would be an option once the initial formatting is done. This all depends on whether "self hosting" means formatting with `HEAD` or the most recent release.

**Comment by tfausak** [comment]
That would probably be fine, especially with layout stability (#235). In fact it might be nice — we could recommend that other projects do that too, and we'd be eating our own dog food.

**Comment by tfausak** [comment]
I'm not sure this is possible. Brittany doesn't handle CPP, and Brittany's own source code has plenty of that. 

``` sh
$ rg --glob '*.hs' '^#' | wc -l
200
```
