### ISSUE TITLE
Using operators beginning with : (colon) in prefix notation leads to a "syntactically invalid result"

### ISSUE THREAD

**Issue by JakobBruenker** [lspitzner/brittany#256]
```haskell
f ((:) a as) = undefined
```

leads to `ERROR: brittany pretty printer returned syntactically invalid result.`

The same happens for any other operator that starts with `:`.

This doesn't happen with

```haskell
f (a : as) = undefined
```

(Ironically, the reason I'm using them in prefix notation is because hlint can *only* deal with `(:#)` in prefix notation.)

**Comment by lspitzner** [comment]
Fixed in 702b993dabe54efdf0736a469df40e04dc2c9a8b, will merge into master once tests are green.

**Comment by tfausak** [comment]
Looks like this is fixed, at least in version 0.12.1.1.
