### ISSUE TITLE
Improve hexagoxel.de/brittany - config and newer GHC in backend

### ISSUE THREAD

**Issue by lspitzner** [lspitzner/brittany#262]
This is somewhat low priority, but I would like to add the following two changes in:

- Use ghc-8.6 in the backend, because some syntax (`DerivingVia`) is only supported since that;
- Allow configuration; most importantly some people might be interested in the "diffing-friendly" modes of operation (IndentPolicyLeft + AlignModeNone or how they are called).

**Comment by tfausak** [comment]
I think this has been implemented. Please re-open if that's not the case.
