### ISSUE TITLE
Support ghc-8.10

### ISSUE THREAD

**Issue by lspitzner** [lspitzner/brittany#269]
The next alpha is released (https://mail.haskell.org/pipermail/ghc-devs/2019-November/018337.html).

For the last two ghc released I have tried to prepare for the next GHC release ahead of time by using head.hackage or whatsitcalled. Because getting that to work has proven to be a sink of my time, this time around I plan _not_ to start working on making brittany compatible until the dependencies work with the new GHC version (excluding the dependencies from me, of course, i.e. multistate/butcher/czipwith/data-tree-print).

This may delay a release that is compatible with ghc-8.10 a bit (but we'll keep making releases with new features until then).

You are very welcome to

- Give feedback on this;
- Mention any new syntactical constructs in 8.10 that you would like to be supported by brittany;
- Friendly poke dependency maintainers about making compatible releases;
- Remind me about this once dependencies are working.

Thank you for your understanding, have a nice day!

**Comment by lspitzner** [comment]
cabal-install is at this moment [not officially compatible](https://github.com/haskell/cabal/issues/5819#issuecomment-566478180) with ghc-8.8 yet. Probably just a bounds oversight, but good to see that brittany is ahead of the "official" ecosystem.

**Comment by ChickenProp** [comment]
Will [ghc-exactprint](https://github.com/alanz/ghc-exactprint) need to be updated for 8.10 before brittany can be? That repo hasn't seen much activity lately.

**Comment by lspitzner** [comment]
yes, but I am sure alanz will make a release in time. I know none of the feature-requests in that repo get much attention, but it has always been updated to new ghcs quickly in the past. And there already is https://github.com/alanz/ghc-exactprint/commits/ghc-8.10.

**Comment by ChickenProp** [comment]
Ah, I hadn't looked at the list of branches. It totally makes sense that that work wouldn't be on master yet.

**Comment by jgrosso** [comment]
Bumping now that GHC 8.10.1 has been officially released.

**Comment by jgrosso** [comment]
@lspitzner I took a brief look, and (at least on Hackage) I _think_ all the external dependencies support GHC 8.10.2.

**Comment by jneira** [comment]
I am afraid that some of them still does not support them. I got several solver errors trying to build it in windows with `cabal v2-build -w ghc-8.10.1` and it needed this cabal project:

```
packages: .

allow-newer: multistate:base,
             data-tree-print:base,
             czipwith:base,
             czipwith:template-haskell,
             butcher:base
```
It could serve as the checklist of packages that would be need an update to be comatible with ghc-8.10.1.

Then i started to fix the compile errors, mainly due to the reorganization of ghc modules (HsSyn -> GHC.Hs and so on)
After fixing some module names with CPP, I am just reach a incompatible function change error:
```
[13 of 32] Compiling Language.Haskell.Brittany.Internal.ExactPrintUtils ( src\Language\Haskell\Brittany\Internal\ExactPrintUtils.hs, D:\\dev\ws\haskell\brittany\dist-newstyle\build\x86_64-windows\ghc-8.10.1\brittany-0.12.1.1\build\Language\Haskell\Brittany\Internal\ExactPrintUtils.o )

src\Language\Haskell\Brittany\Internal\ExactPrintUtils.hs:101:9: error:
    • Couldn't match type ‘Bag.Bag ErrUtils.ErrMsg’ with ‘(a1, [Char])’
      Expected type: Either
                       (a1, [Char]) (ExactPrint.Anns, GHC.ParsedSource)
        Actual type: Either
                       ErrUtils.ErrorMessages (ExactPrint.Anns, GHC.ParsedSource)
    • In the second argument of ‘($)’, namely
        ‘ExactPrint.postParseTransform res opts’
      In a stmt of a 'do' block:
        either
          (\ (span, err) -> ExceptT.throwE $ show span ++ ": " ++ err)
          (\ (a, m) -> pure (a, m, x))
          $ ExactPrint.postParseTransform res opts
      In the second argument of ‘($)’, namely
        ‘do dflags0 <- lift $ GHC.getSessionDynFlags
            (dflags1, leftover, warnings) <- lift
                                               $ GHC.parseDynamicFlagsCmdLine
                                                   dflags0
                                                   (GHC.noLoc <$> ("-hide-all-packages" : args))
            void $ lift $ GHC.setSessionDynFlags dflags1
            dflags2 <- lift $ ExactPrint.initDynFlags fp
            ....’
    |
101 |       $ ExactPrint.postParseTransform res opts
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src\Language\Haskell\Brittany\Internal\ExactPrintUtils.hs:132:13: error:
    • Couldn't match type ‘(a0, [Char])’ with ‘Bag.Bag ErrUtils.ErrMsg’
      Expected type: ErrUtils.ErrorMessages
        Actual type: (a0, [Char])
    • In the pattern: (span, err)
      In the pattern: Left (span, err)
      In a case alternative:
          Left (span, err)
            -> ExceptT.throwE $ showOutputable span ++ ": " ++ err
    |
132 |       Left  (span, err) -> ExceptT.throwE $ showOutputable span ++ ": " ++ err
```
😞

**Comment by jneira** [comment]
My work so far is here: https://github.com/lspitzner/brittany/compare/master...jneira:ghc-8.10.1?expand=1
Just in case it could be useful
