### ISSUE TITLE
Cabal v1 instructions are just fine

### ISSUE THREAD

**Issue by ivanperez-keera** [lspitzner/brittany#274]
Hi,

The readme contains a line that says:
> (TODO: These instructions are more confusing than helpful. I am inclined to just remove them.)

I have just used the v1 option and it works just fine (it's been my preferred way of installing packages with Haskell since it first came out).

Except for new-build, the instructions are actually pretty simple. I'd suggest replacing those instructions with something just formatted clearly:

* Cabal 3.0:
`cabal install brittany --installdir=$HOME/.cabal/bin`
Cabal merely puts a symlink to the "store" into the installdir, so you have to re-install if you ever clean your store.
* Cabal 2.4 (v2)
`cabal v2-install brittany`
* Cabal 2.2 (new-build):
`cabal new-build exe:brittany; cp $(find dist-newstyle/ -name brittany -type f | xargs -x ls -t | head -n1) $HOME/.cabal/bin/`
* Cabal 2.2 (v1, with sandboxes):
`cabal v1-sandbox init; cabal v1-install brittany --bindir=$HOME/.cabal/bin`

**Comment by tfausak** [comment]
If you'd like to open a PR making these changes, I'd be happy to merge it :smile:
