### ISSUE TITLE
Consider directly abutting record braces to the constructor name in patterns

### ISSUE THREAD

**Issue by expipiplus1** [lspitzner/brittany#284]
I was certain there was an issue already for this, but I couldn't find it.

Would it make sense to have no space between the record constructor name and the opening brace:

```haskell
-- This
foo Bar{..} baz = noo Qux{ .. } boo

-- Currently it's this
foo Bar {..} baz = noo Qux { .. } boo
```

Although it's certainly no big deal, removing the space would make the precedence of the expression/pattern clearer.

At the moment at a quick glance one might thing `foo` and `noo` have arity three; without the space it's clear that the record contents are binding tightly to the constructor.

**Comment by expipiplus1** [comment]
Indeed this already happens for *empty* braces

**Comment by expipiplus1** [comment]
This might only look nice for single line record updates/matches however. And the consistency between single and multi line behavior is worth paying attention to.

**Comment by lspitzner** [comment]
See https://github.com/lspitzner/brittany/issues/251

**Comment by expipiplus1** [comment]
I knew it!
