### ISSUE TITLE
publish on Hackage

### ISSUE THREAD

**Issue by lspitzner** [lspitzner/brittany#29]
ToDos:

- [x] publish `butcher` on hackage;
- [x] publish `data-tree-print` on hackage;
- [x] publish `czipwith` on hackage and use it for config (replace local CZip);
- [x] ~~consider replacing lens with some micro variant~~ remove lens dependency;
- [x] add bounds for all deps;
- [x] fill metadata (synopsis, description, copyright etc.)
- [x] update changelog
- [x] choose/add license
- [x] prepare announcement

**Comment by Hrothen** [comment]
The remaining requirements (metadata and license) seem to be fulfilled on `dev`, any chance we might get a release soon?

**Comment by lspitzner** [comment]
@Hrothen you are right, sorry for the delay. I let myself get sidetracked by minor issues multiple times; just yesterday I noticed that

~~~~.hs
act v = SVectorBase.withStartPtr v $ \ptr _ ->
  case MemoryPool.getPtrFragmentation poolDataSnapshot ptr of
    Just (_, ratio) | ratio>1.001 -> error "should not happen"
    Just (f, ratio) | f, ratio<limit -> do
      v' <- MemoryPool.vectorCopyPool pool v
      performMinorGC
      return v'
    _ -> return v
~~~~

turns into

~~~~.hs
act v =
  SVectorBase.withStartPtr v
    $ \ptr _ -> case MemoryPool.getPtrFragmentation poolDataSnapshot ptr of
        Just (_, ratio) | ratio > 1.001    -> error "should not happen"
        Just (f, ratio) | f, ratio < limit -> do
          v' <- MemoryPool.vectorCopyPool pool v
          performMinorGC
          return v'
        _ -> return v
~~~~

which is annoyingly non-optimal. These things nag at you when you planned to use this or a similar piece of code in showcases.

But it really is time to make a release - I'll upload a candidate today and do the release tomorrow.

**Comment by lspitzner** [comment]
candidate at http://hackage.haskell.org/package/brittany-0.8.0.2/candidate
