### ISSUE TITLE
Support formatting GADTs

### ISSUE THREAD

**Issue by lspitzner** [lspitzner/brittany#298]
This is one more part of #47. Also, unfortunately currently GADT formatting is slightly broken, even though brittany forwards GADT layouting to `ghc-exactprint`:

~~~~.hs
data Foo x where
  A :: Int -> Foo Int
  B :: Bool -> Foo Bool
-- is roundtripped to
data Foo x where
  A ::Int -> Foo Int
  B ::Bool -> Foo Bool
~~~~

Which I guess is another context-sensitive bug in ghc-exactprint. Might depend on the ghc version used. Easiest fix probably is to

**Comment by tfausak** [comment]
I'm closing this as a duplicate of #217.
