### ISSUE TITLE
Show which files (or ideally where in the file requires change)

### ISSUE THREAD

**Issue by CMCDragonkai** [lspitzner/brittany#314]
I'm using formatters like `prettier` (typescript) and `black` (python) to ensure autoformatting of source code.

Brittany looks great, but I've been looking at the option `--check-mode` to integrate the CI.

The problem is that brittany does not show which file failed formatting checks and doesn't show which line it occurred on.

Currently the `--verbose` option is not doing anything. Perhaps the `--verbose` can be used to show which lines or at least which file failed the formatting check.

**Comment by tfausak** [comment]
I'm not sure when exactly this changed, but as of Brittany 0.13.0.0 you will get output about which files are unformatted:

``` sh
$ cat gh314.hs 
unformatted=True

$ brittany --check-mode gh314.hs 
formatting would modify: gh314.hs
```
