### ISSUE TITLE
Overloaded labels syntax is destroyed

### ISSUE THREAD

**Issue by majkrzak** [lspitzner/brittany#320]
When running `brittany` over [OverloadedLabels](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/overloaded_labels.html) (`#foo`) it gets destroyed by appending space between `#` and `foo`.

**Comment by arybczak** [comment]
It should work if you put `-XOverloadedLabels` in `options_ghc` in `brittany.yaml`.

**Comment by tfausak** [comment]
I can confirm that Brittany handles overloaded labels just fine:

``` sh
$ brittany --version
brittany version 0.13.0.0
Copyright (C) 2016-2019 Lennart Spitzner
Copyright (C) 2019 PRODA LTD
There is NO WARRANTY, to the extent permitted by law.

$ cat example.hs
{-# language OverloadedLabels #-}
someLabel = #some

$ brittany < example.hs
{-# language OverloadedLabels #-}
someLabel = #some
```

**Comment by majkrzak** [comment]
Same here, I can't reproduce. Might be something went wrong with my build script and extension was not detected correctly. Sorry.
