### ISSUE TITLE
Brittany Roadmap

### ISSUE THREAD

**Issue by vaclavsvejcar** [lspitzner/brittany#322]
First of all, big thanks to @lspitzner, @eborden, @tfausak and all other contributors for Brittany. It's really awesome tool I use daily for my Haskell projects. In general, I'm really happy how tooling around Haskell went forward in last year (or so), for example HLS, that really makes lot of things easier compared to HIE. But I'm kinda worried about the progress in Brittany. No offense at all - I fully understand this is opensource project done by people in their free time, but it would be so pity if development of this tool would stuck or eventually die at all (I really really don't want to move to Ormolu 😀). For example, there are some opened tickets (#315, #318, etc) and pull requests (#294, #312) that would be nice to have finished and released.

So I'd like to know if there's any roadmap for Brittany at this moment? I don't feel experienced enough to directly contribute (maybe if you have some low hanging fruit kind of tasks), but I was wondering if you (current authors/contributors) don't have enough resources (time or money), have you considered any other way how to support Brittany? For example allow sponsorship, look for some investors, experienced developers, etc?

Again, big thanks guys for all your work, thanks a lot in advance and stay safe! 🙂

**Comment by tfausak** [comment]
I'm pretty much here to do meta work: triaging issues, making releases, and so on. I can make basic changes to the code but anything more advanced is beyond me. 

As far as I'm concerned this is @lspitzner's project, so any road mapping is up to him.

**Comment by tfausak** [comment]
I’m going to close this issue for now. See #358.
