### ISSUE TITLE
Indents on `where` clauses don't always follow the brittany.yaml settings (4-spaces)

### ISSUE THREAD

**Issue by j127** [lspitzner/brittany#336]
What I expect to happen: 4-space indentation

What actually happens: 2-space indentation for multi-line `where` clauses (while everything else has 4 spaces, including single-line `where` clauses)

Versions:

- brittany version 0.12.2.0
- ghc version 8.9.4
- ubuntu 20.04

My `brittany.yaml` file contains the line:

```yaml
lconfig_indentAmount: 4
```

Everything works great so far, except in one case. When I run brittany on this code:

```haskell
solveRPN :: (Num a, Read a) => String -> a
solveRPN = head . foldl foldingFunction [] . words
    where
        foldingFunction (x : y : ys) "*"          = (x * y) : ys
        foldingFunction (x : y : ys) "+"          = (x + y) : ys
        foldingFunction (x : y : ys) "-"          = (y - x) : ys
        foldingFunction xs           numberString = read numberString : xs
````

brittany changes it to 2-space indentation:

```haskell
solveRPN :: (Num a, Read a) => String -> a
solveRPN = head . foldl foldingFunction [] . words
  where
    foldingFunction (x : y : ys) "*"          = (x * y) : ys
    foldingFunction (x : y : ys) "+"          = (x + y) : ys
    foldingFunction (x : y : ys) "-"          = (y - x) : ys
    foldingFunction xs           numberString = read numberString : xs
````
It looks like it only happens for `where` clauses when there are multiple lines. When there is just one line, it correctly indents by 4 spaces:

```haskell
calcBmis :: (RealFloat a) => [(a, a)] -> [a]
calcBmis xs = [ bmi w h | (w, h) <- xs ]
    where bmi weight height = weight / height ^ 2
```
If I change that code to 2 spaces and run brittany on it, it correctly re-indents it with 4 spaces (based on my config file).

**Comment by tfausak** [comment]
I think you can avoid this by setting `lconfig_indentWhereSpecial: false`. See #39 and #188.

**Comment by j127** [comment]
Thanks, that fixed it. 

(Sorry, I had searched through the issues before posting but didn't see those.)
