### ISSUE TITLE
Version 0.13.1.1 is not released on https://hackage.haskell.org/

### ISSUE THREAD

**Issue by bobbui** [lspitzner/brittany#345]
URL https://hackage.haskell.org/package/brittany-0.13.1.1 is a not found page

also try to install by **stack** throw this error:
```
stack install brittany-0.13.1.1

Error: While constructing the build plan, the following exceptions were encountered:

Unknown package: brittany

Some different approaches to resolving this:


Plan construction failed.
```

Please help to release latest version. Thanks a lot

**Comment by tfausak** [comment]
Oops, sorry about that! It should be available now: https://hackage.haskell.org/package/brittany-0.13.1.1
