### ISSUE TITLE
Release says "Missing file: /home/runner/.ghcup/ghc/8.10.2/lib/ghc-8.10.2/settings"

### ISSUE THREAD

**Issue by unhammer** [lspitzner/brittany#350]
tried running the file in releases→brittany-0.13.1.2-ubuntu.zip on ubuntu 20.04 and it just gives "Missing file: /home/runner/.ghcup/ghc/8.10.2/lib/ghc-8.10.2/settings"

**Comment by tfausak** [comment]
I think this is the same as #315.

**Comment by unhammer** [comment]
oh how did I not see that; seems like exactly the same, yes! I'll close then.
