### ISSUE TITLE
brittany-0.14.0.1 has breaking changes

### ISSUE THREAD

**Issue by jneira** [lspitzner/brittany#364]
In that [hackage version](https://hackage.haskell.org/package/brittany) all modules has been renamed dropping the `Haskell.Language` prefix, breaking the hls plugin (and everything else using the package as a lib I guess)
I can't see that version in master in this git repo
The version was uploaded by fozworth at 2022-01-11T14:16:35Z

Not sure what is going on (I suppose it has been an erroneous upload) but imo it should be reverted asap
Thanks in advance
/cc @tfausak @lspitzner

**Comment by tfausak** [comment]
Oops, that should have been 0.15.0.0. 

I'm maintaining Brittany over at <https://github.com/tfausak/brittany> since I don't have admin access to this repo.

**Comment by tfausak** [comment]
I deprecated version 0.14.0.1 on Hackage. I'm reverting https://github.com/tfausak/brittany/commit/2fe1432631ac103284729c9afbbf0b0045228150, then I'll release 0.14.0.2 and bring this repo up to date with tfausak/brittany.

**Comment by tfausak** [comment]
0.14.0.2 should be published to Hackage as soon as this job finishes: https://github.com/tfausak/brittany/actions/runs/1693179240

**Comment by michaelpj** [comment]
Thank you for the incredibly fast response!

**Comment by tfausak** [comment]
Sorry for breaking it in the first place 😆 

https://hackage.haskell.org/package/brittany-0.14.0.2
