### ISSUE TITLE
`lconfig_indentAmount` not respected for `where` clauses when `lconfig_indentWhereSpecial` is on

### ISSUE THREAD

**Issue by fmthoma** [lspitzner/brittany#39]
Config:
Default config except for `lconfig_indentAmount = 4` (rather than `2`).

Example:

```haskell
main = foo                 
  where
    foo = do    
        putStrLn "Hello"
        putStrLn "World"
```

Output:

```haskell
main = foo
 where
  foo = do
      putStrLn "Hello"
      putStrLn "World"
```

Expected: Output same as input (`where` indented by two spaces, `foo = do …` by four), rather than one and two space, respectively.

**Comment by lspitzner** [comment]
thanks for reporting! Haven't tested extensively, but it seems simple enough.

**Comment by fmthoma** [comment]
Tried it on dev branch, works :-) Thank you!
