### ISSUE TITLE
What editor is that in the Readme gif?

### ISSUE THREAD

**Issue by ShadowCreator** [lspitzner/brittany#43]

**Comment by lspitzner** [comment]
It is sublime-text-3, and I use the filter-through-command plugin, which I customized slightly to improve this and related use-cases. If desired I could upload the updated plugin.

(I have also bound a key to do exactly what I do there, so I can select some top-level function and have it auto-formatted via one keypress; or auto-format the whole file if nothing is selected.)

**Comment by moodmosaic** [comment]
Just wondering, what other tools do you use for doing Haskell development in Sublime Text?

**Comment by moodmosaic** [comment]
>If desired I could upload the updated plugin

Yes, I think that would be beneficial 👍

**Comment by lspitzner** [comment]
@moodmosaic done, see https://gist.github.com/lspitzner/097c33177248a65e7657f0c6d0d12075

**Comment by moodmosaic** [comment]
@lspitzner Lovely setup ❤️ I left a comment there.
