### ISSUE TITLE
Does brittany have a plan to comply with XDG Base Directory Spec?

### ISSUE THREAD

**Issue by expipiplus1** [lspitzner/brittany#45]
It might be best to store the configuration in `$XDG_CONFIG_HOME/brittany/config.yaml` (typically `~/.config/brittany/config.yaml`

**Comment by lspitzner** [comment]
If not for backwards-compatibility, this should be no more than `s/getAppUserDataDirectory/getXdgDirectory XdgConfig/` over in [Main.hs:L294](https://github.com/lspitzner/brittany/blob/baac0a6a7e74ea70cae02c4d317e4a24bce8e9b8/src-brittany/Main.hs#L294). Even when HIE users won't even see this, I had planned to keep compatibility. Maybe that's too ambitious..

anyway, PR welcome.

**Comment by expipiplus1** [comment]
Thanks!
