### ISSUE TITLE
Type application with Nats or Symbols upsets let alignment

### ISSUE THREAD

**Issue by expipiplus1** [lspitzner/brittany#48]
Compare:

```haskell
foo =
  let a = b @1
      cccc = ()
  in  foo

foo =
  let a = b @""
      cccc = ()
  in  foo

foo =
  let a    = b @d
      cccc = ()
  in  foo

foo =
  let a    = b @D
      cccc = ()
  in  foo
```

**Comment by lspitzner** [comment]
Right, this most likely comes down to [this case lacking a proper implementation](https://github.com/lspitzner/brittany/blob/ebf84a03e939ad1017cc741339d0ec7e4080e776/src/Language/Haskell/Brittany/Internal/Layouters/Type.hs#L602-L603). Although I am a bit confused why it does not work as-is; how `layoutByExact` works but inhibits alignment.. will investigate later.

**Comment by lspitzner** [comment]
Fixed on `dev` branch

**Comment by expipiplus1** [comment]
Thanks!
