### ISSUE TITLE
RecursiveDo "do rec" is not supported

### ISSUE THREAD

**Issue by ElvishJerricco** [lspitzner/brittany#58]
`RecursiveDo` supports a secondary syntax that a lot of Reflex users like to use.

```haskell
foo = do
  rec a <- f b
      b <- g a
  return (a, b)
```

**Comment by lspitzner** [comment]
`mdo` is supported though. I don't know if either syntax is generally preferred; I'd be interested if you have a good reason to prefer `rec`. (Of course i'd like to support `rec` as well eventually.)

**Comment by ElvishJerricco** [comment]
At this point the biggest reason is convention. It’s become much more conventional in Reflex to use `rec`. But the technical reason is that you have control over where the `mfix`s get placed and how big they are, which can matter for performance. It’s also just more explicit about which parts are recursive, which helps readability.

**Comment by lspitzner** [comment]
Can anyone think of other interesting testcases? the syntax node [has 10 fields](https://downloads.haskell.org/~ghc/8.2.1/docs/html/libraries/ghc-8.2.1/HsExpr.html#v:RecStmt) and i process one of those, feels like i miss something.. but for the one above it works.

**Comment by lspitzner** [comment]
Well, this still lacks a bit more testcases, but I'll optimistically close this.
