### ISSUE TITLE
Keep newlines

### ISSUE THREAD

**Issue by alexkazik** [lspitzner/brittany#61]
Would it be possible to add a new option which keeps all newlines but formats everything else (like indentation, too many/less space, ..)?

**Comment by lspitzner** [comment]
The answer to such questions always is "if you put enough work into it, sure".. but having thought a moment about this, I suspect it would need a lot of effort, and even then it seems not compatible with `brittany`'s current mode of operation.

It might be possible to do something weaker: To take into account if a syntax node currently is in a newline when considering/choosing one of the alternatives in the `BriDoc` representation. This may require an acceptable amount of work to implement, but I am not certain if this would come sufficiently close to what you want, and I have no interest in doing it.

You may want to have a look at https://github.com/ocharles/hsfmt though; afaik that project tries exactly what you describe and it is based on `ghc-exactprint`, too. Not sure how active it is or if it is usable at all yet.

**Comment by alexkazik** [comment]
Thanks for the reply and information.
Thought it wouldn't be that easy but asked anyway.
