### ISSUE TITLE
Formatting error (run-together identifiers)

### ISSUE THREAD

**Issue by eschnett** [lspitzner/brittany#67]
Using `brittany` on this fragment introduces an error.

Input:
```
fmapuv :: U.Unbox a => (a -> b) -> U.Vector a -> V.Vector b
fmapuv f xs = G.generate (G.length xs) (f . (xs G.!))
```

Output:
```
fmapuv :: U.Unbox a => (a -> b) -> U.Vector a -> V.Vector b
fmapuv f xs = G.generate (G.length xs) (f . (xsG.!))
```

The expression `xs G.!` (apply operator `!` imported from module `G`) gets mis-printed as `xsG.!` (operator `!` from module `xsG`), i.e. a space is missing.

I just updated Brittany from Github:
```
$ brittany --version
brittany version 0.8.0.3
```

**Comment by lspitzner** [comment]
Right. Is anyone opposed to changing whitespace handling in sections to always insert whitespace between argument and operator? I think this would be a more established default. Some use exceptions for (:) and arithmetic operators, but I could do without exceptions.

**Comment by eschnett** [comment]
I could do without exceptions.

I thought that Brittany had internal fail-safes to prevent misprints like this, i.e. that the emitted code parses back to the same syntax tree. How did this fail in this case?

**Comment by lspitzner** [comment]
That's a good point. The current failsafe only tests that the output is syntactically valid, which it is in this case. Checking that the (not location-dependent parts of the) syntaxtrees remain equal is a good idea. I'll open a new ticket for that.
