### ISSUE TITLE
Brittany not idempotent -- spaces get inserted

### ISSUE THREAD

**Issue by eschnett** [lspitzner/brittany#68]
Brittany inserts one additional space every time it is run on this expression.

This is the original input:
```
cs0 = 0 : [ c / Interval n | c <- cs | n <- [1..] ]
```

The first output is:
```
cs0 = 0 : [ c / Interval n |  c <- cs | n <- [1..] ]
```
with an additional space before `c <- cs`. Each run inserts an additional space there.

This is with
```
$ brittany --version
brittany version 0.8.0.3
```

**Comment by lspitzner** [comment]
(This is `-XParallelListComp`, right?)

This is more or less a bug in the workaround code for (yet) unhandled extensions. I have just added a `Text.trim` which fixes this particular issue, but this workaround fixup might break other such cases (for other unhandled extensions..)

The real fix is of course to support `-XParallelListComp`, which is the only way to properly and safely support multiline parallel list comps. I don't have time to implement this. PR welcome.

**Comment by lspitzner** [comment]
Nonetheless I will consider this fixed. Please open another issue if you desire support for `-XParallelListComp`.
