### ISSUE TITLE
Format let and in on a single line if they fit

### ISSUE THREAD

**Issue by tfausak** [lspitzner/brittany#73]
https://github.com/lspitzner/brittany/pull/66#issuecomment-348820992

Using the currently unreleased `IndentPolicyLeft`/`ColumnAlignModeDisabled` config, Brittany formats `let ... in ...` like this:

``` hs
_ =
  let
    longIdentifierForShortValue = 1
  in
    longIdentifierForShortValue + longIdentifierForShortValue
```

I expected both `let` and `in` to be on a single line, like this:

``` hs
_ =
  let longIdentifierForShortValue = 1
  in longIdentifierForShortValue + longIdentifierForShortValue
```

**Comment by lspitzner** [comment]
Indeed, the approach from 882a3b1a7a7851b36fb147580ad36eda2d28abc6 can be applied to the relevant layouter in `Expr.hs` too. I am a bit unsure though which combinations should be accepted, i.e. should the following layouts be possible:

~~~~.hs
_ =
  let singlelinebinder = 1
  in
    some
      multiline
      expression
-- and
_ =
  let
    some long stuff = do
      blah
      blub
  in singleline expression
~~~~

this boils down to permitting layouters
"let (single|multiline) in (single|multiline)" vs
"(let singleline in singleline | let multiline in multiline)"

**Comment by tfausak** [comment]
I would prefer "let (single|multiline) in (single|multiline)". I don't particularly care about them matching; I want them to avoid wasting vertical space.

``` hs
a =
  let it = foo
  in it
-- maybe even `a = let it = foo in it` if everything fits
-- not sure if it's like that already
b =
  let
    it = do
      foo
      bar
  in it
c =
  let it = foo
  in -- maybe start long expression here instead of next line
    do
      it
      bar
d =
  let
    it = do
      foo
      bar
  in
    do
      it
      baz

**Comment by eborden** [comment]
@lspitzner I believe you can close this with the merger of #97
