### ISSUE TITLE
Section layout oddity

### ISSUE THREAD

**Issue by sniperrifle2004** [lspitzner/brittany#80]
Currently brittany formats a section like this:

```haskell
s = (+12)
```
In this case that is not so bad, but if you infix a function or the argument is a more complicated expression it becomes a little awkward (imho):

```haskell
s' = (++show 12)
s'' = (`subtract`12)
```
I think it would be better to always have a space between the operator and the operand. Or at least have one if the section is no longer trivial (But what is trivial might be hard te establish)

**Comment by lspitzner** [comment]
This was fixed in 0.9.0.0 (see #67). Did indeed choose against any "simple-case" special-casing.
