### ISSUE TITLE
brittany gives an error if all module elements are indented

### ISSUE THREAD

**Issue by sniperrifle2004** [lspitzner/brittany#81]
For modules with (Accidental) additional indentation like this:

```haskell
module Main (main) where
  import Data.List
   
  main = return ()
```
Running brittany raises an error:
```
$ britanny < Test.hs
ERROR: brittany pretty printer returned syntactically invalid result.
```

**Comment by lspitzner** [comment]
I mentioned a potential solution to this in #42: Retaining "initial indentation" should fix this (brittany would then act as identity on your example).

**Comment by sniperrifle2004** [comment]
Ah I think I understad. Because brittany does nothing with imports yet and it doesn't preserve initial indentation the resulting code becomes invalid.

While preserving initial indentation would certainly serve as a solution, I am not sure that would be my final choice.  I would like brittany to format the code according to a specified set of rules. If these rules specify that there should be no initial indentation, there should be none.  For that to work, however, there will have to be at least rudementary layouters for top level elements,

**Comment by lspitzner** [comment]
Yeah, agreed. The only real fix for that is to properly handle all top-level module elements (and imports are not the only thing not handled yet).

**Comment by tfausak** [comment]
Sounds like this might get tied up with #155.

**Comment by tfausak** [comment]
I'm not sure when this was fixed, but it doesn't seem to be a problem anymore.

``` sh
$ cat > gh81.hs
module M where
  import Control.Monad
  unit = ()

$ brittany gh81.hs
module M where
import           Control.Monad
unit = ()
```
