### ISSUE TITLE
Add config overrides to tests

### ISSUE THREAD

**Issue by sniperrifle2004** [lspitzner/brittany#86]
To be able to test layouters configuration options it may be necessary to override config values for a given (set of) test(s). This is currently done for global alignment options by having a whole set of separate tests, but more layouter specific are likely to pop up and such an approach is not going to hold up.

Maybe an optional yaml document for test groups? it could be embedded in the group header.

**Comment by lspitzner** [comment]
This is solved in a more general fashion by #30. Especially see [this comment](https://github.com/lspitzner/brittany/issues/30#issuecomment-333583994).

And yes I somewhat forgot about that branch. Most of the implementation was finished, apart from the things that affect the next binding when there are multiple next bindings. I probably should get it finished up asap.
