### ISSUE TITLE
Extra space after opening parenthesis

### ISSUE THREAD

**Issue by chreekat** [lspitzner/brittany#87]
brittany produces the following:

```
x = fmap
  (map entityVal)
  ( selectList [Model.CrowdmatchHistoryPatron ==. pid]
               [Asc Model.CrowdmatchHistoryDate]
  )
```

I would expect this instead:

```
x = fmap
  (map entityVal)
  (selectList [Model.CrowdmatchHistoryPatron ==. pid]
              [Asc Model.CrowdmatchHistoryDate])
```

The location of the closing parenthesis, of course, could be a matter of taste. But that opening space seems to indicate brittany is expecting a tuple rather than a precedence-defining, single-element parenthetical.

**Comment by lspitzner** [comment]
hmm, the space could be changed using

~~~~
@@ -327,7 +327,7 @@ layoutExpr lexpr@(L _ expr) = do
           ]
         , docSetBaseY $ docLines
           [ docCols ColOpPrefix
-            [ docParenLSep
+            [ docLit $ Text.pack "("
             , docAddBaseY (BrIndentSpecial 2) innerExpDoc
             ]
           , docLit $ Text.pack ")"
~~~~

and that seems indeed nicer.
The closing parenthesis is a different matter, for cases like

~~~~.hs
layoutIE lie@(L _ ie) = a
  (  intersperse
      docCommaSep
      (map ((docLit =<<) . lrdrNameToTextAnn . prepareName) nsaaaaaaaaaa)
  ++ intersperse docCommaSep (map prepareFL fs)
  )
~~~~

where the alternative would be..  

~~~~.hs
layoutIE lie@(L _ ie) = a
  (intersperse
      docCommaSep
      (map ((docLit =<<) . lrdrNameToTextAnn . prepareName) nsaaaaaaaaaa)
    ++ intersperse docCommaSep (map prepareFL fs))
~~~~

right? or perhaps

~~~~.hs
layoutIE lie@(L _ ie) = a
  (  intersperse
      docCommaSep
      (map ((docLit =<<) . lrdrNameToTextAnn . prepareName) nsaaaaaaaaaa)
  ++ intersperse docCommaSep (map prepareFL fs))
~~~~

I think i like the first option the most. There is a more fundamental reason for this behaviour, too: It is really hard to decide (with brittanys algorithm) if there is sufficient space in the last line of the child node to append the closing parenthesis. Possible to adapt the algorithm, but a good bit of low-level changes.

I'll wait for feedback for a bit; default action will be to apply the above diff resulting in these layouts:

~~~~.hs
x = fmap
  (map entityVal)
  (selectList [Model.CrowdmatchHistoryPatron ==. pid]
              [Asc Model.CrowdmatchHistoryDate]
  )

layoutIE lie@(L _ ie) = a
  (  intersperse
      docCommaSep
      (map ((docLit =<<) . lrdrNameToTextAnn . prepareName) ns)
  ++ intersperse docCommaSep (map prepareFL fs)
  )
~~~~

**Comment by chreekat** [comment]
Proposed action sounds great to me.

**Comment by eborden** [comment]
I'm in favor of keeping the line break before the closing paren.

**Comment by lspitzner** [comment]
Implemented as proposed.
