### ISSUE TITLE
ghc "impossible" triggered when alignmentLimit set to 0

### ISSUE THREAD

**Issue by chreekat** [lspitzner/brittany#88]
Input:

```
x =
  let g   = "foo"
      ghi = "bar"
  in  g ++ ghi
```

Output (after setting conf_layout.lconfig_alignmentLimit: 0)

```
brittany: panic! (the 'impossible' happened)
  (GHC version 8.0.2 for x86_64-unknown-linux):
	Prelude.maximum: empty list

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

**Comment by lspitzner** [comment]
No `ghc` bug; the panic is just a side-effect of an exception in chunks passed to the ghc parser. Of course stilll a bug in `brittany`. Hope you only reported it here so far :p

**Comment by lspitzner** [comment]
most likely due to this: [`colAggregation xs = maximum [ x | x <- xs, x < minimum xs + alignMax ]`](https://github.com/lspitzner/brittany/blob/ac10b903af3d6814dc52e78e8ad52a81a20d3ee1/src/Language/Haskell/Brittany/Internal/Backend.hs#L355).

**Comment by chreekat** [comment]
I tried making that total, but it didn't seem to help. And yeah I'm only reporting here. :) Even if it ends up being a bug lower down, I wouldn't know where in the dep tree it might be.

**Comment by lspitzner** [comment]
Btw, even if it should not crash, this value does not make much sense semantically: `lconfig_columnAlignMode: ColumnAlignModeDisabled` is probably more suited to express "only use up to 0 spaces to achieve alignment". What effect were you going for with this config?

**Comment by chreekat** [comment]
Indeed, setting it to 1 gives the behavior I desire. Which I suppose is
equivalent to disabling column align mode? I was just flailing at the
config file to see what effect different settings had, and I'm still
figuring out what some of them mean. :)

On Dec 21, 2017 15:25, "Lennart Spitzner" <notifications@github.com> wrote:

Btw, even if it should not crash, this value does not make much sense
semantically: lconfig_columnAlignMode: ColumnAlignModeDisabled is probably
more suited to express "only use up to 0 spaces to achieve alignment". What
effect were you going for with this config?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lspitzner/brittany/issues/88#issuecomment-353449424>,
or mute the thread

**Comment by lspitzner** [comment]
And I cannot reproduce after making it total via `maximum . (0 :)`

**Comment by chreekat** [comment]
Aha, I was using `colAggregation [] =  {0|maxBound}`

At this point, I think this is a fairly low-priority bug: I won't mind if you close it (though I leave it up to you). Thanks! So far I like brittany a lot.

**Comment by lspitzner** [comment]
thanks! I have included two fixes to be sure. Having `<=` instead of `<` there is probably more correct anyways.
