### ISSUE TITLE
View Patterns

### ISSUE THREAD

**Issue by ElvishJerricco** [lspitzner/brittany#9]
I've come to really like view patterns, but Brittany won't even try to format a file with them. I imagine this shouldn't be too difficult, since view patterns are necessarily contained within parentheses.

**Comment by ElvishJerricco** [comment]
I think both #9 and #10 have been sufficiently solved by 575d530 (the solution to #11). At least they have been in my usage. Should these be closed, or do we want more tailored behavior for every GHC feature?

**Comment by lspitzner** [comment]
Glad to hear that.

> Should these be closed, or do we want more tailored behavior for every GHC feature?

Well, of course I want every GHC feature handled at some point - but I'd rather close for now. No use in having these (and 50 other) case-specific issues open as long as they don't practically cause problems.
