### ISSUE TITLE
shebang disappears from stdin

### ISSUE THREAD

**Issue by cblp** [lspitzner/brittany#92]
The same file gives the different result when is given as an argument or as stdin.

```
$ brittany test.hs | diff test.hs -
$ echo $?
0

$ cat test.hs | brittany | diff test.hs -
1c1
< #!/usr/bin/env stack
---
>
$ echo $?
1
```

Version 0.9.0.0

**Comment by lspitzner** [comment]
This commit fixes it, but I'd like to move some of this code upstream, see the PR above.
