### ISSUE TITLE
"--write-mode inplace" should not write when there are no changes

### ISSUE THREAD

**Issue by eschnett** [lspitzner/brittany#93]
When Brittany does not make any changes to a source file, e.g. because the input was already formatted by Brittany, then it should not modify the file's time stamp. This would prevent unnecessary prompts from the editor to re-load the file.

```
$ brittany --version
brittany version 0.9.0.0
```

**Comment by lspitzner** [comment]
and of course lazy IO managed to bite me on this one. read in file as lazy text, because our output is/was lazy text. compare. if false, handle is not closed, write fails.
